apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/object-effects/base
  - configmap.yaml
  - vault-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: 70dbb08a89da65d0486bdfa9dbf7c83e28534d96
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/ObjectEffectsAPI/actions/runs/35348289446
images:
  - name: urban-assistant/object-effects
    newName: 10.32.11.13:5000/object_effects
    digest: sha256:68e676461681b509332f1311108fc0ce6d38a33709f9a3812a272a2e203a24c9
