apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/object-effects/base
  - configmap.yaml
  - vault-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: 0ecf8340ecbd6c7c002058f4b2c98ec15c168c6c
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/ObjectEffectsAPI/actions/runs/35355500041
images:
  - name: urban-assistant/object-effects
    newName: 10.32.11.13:5000/object_effects
    digest: sha256:db57391e60941d470427c482fd47aad56094d3d3b5141cb529b5b15a610d6c0e
