apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: object-effects-secrets
spec:
  vaultAuthRef: urban-assistant-dev
  mount: urban-assistant-kv
  type: kv-v2
  path: dev/object-effects
  refreshAfter: 1m
  hmacSecretData: true
  destination:
    create: true
    overwrite: false
    name: object-effects-secrets
    type: Opaque
    transformation:
      excludes: [".*"]
      templates:
        SERVICE_AUTH_SERVER_URL:
          text: '{{ get .Secrets "service_auth_server_url" }}'
        SERVICE_AUTH_CLIENT_SECRET:
          text: '{{ get .Secrets "service_auth_client_secret" }}'
  rolloutRestartTargets:
    - kind: Deployment
      name: object-effects
