apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/urban-api/base
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: 7fe385fcb1ec6b96366abd0ac95d36ba1fa258e8
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/idu_api/actions/runs/34150930439
images:
  - name: urban-assistant/urban-api
    newName: 10.32.11.13:5000/urban_api
    digest: sha256:74129744078b2dba5ce19211b1fad5ded466e30cc1e02f9f961f0b77643e6475
  - name: urban-assistant/urban-migrator
    newName: 10.32.11.13:5000/urban_migrator
    digest: sha256:720246f318f727566d0c38e26383c77a2c5b45b0d5cf5d14472b545959b68bc7
patches:
  - path: migration-wait-patch.yaml
