apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/urban-api/base
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: 240b428b19f6b5b9c68442454ed3da1fe67bc32c
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/idu_api/actions/runs/34045126150
images:
  - name: urban-assistant/urban-api
    newName: 10.32.11.13:5000/urban_api
    digest: sha256:1f7e89f13f485dff7be1398a6e4e64f6365ff9f1b29711cfffa7562f87b2b5f8
  - name: urban-assistant/urban-migrator
    newName: 10.32.11.13:5000/urban_migrator
    digest: sha256:fa346dee2c32f66cde245b95d91f076caa30d8fa6de799c748903231486a0c45
patches:
  - path: migration-wait-patch.yaml
