apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/scenarios-conductor/base
  - vault-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: 872a973b23663db999b13a64c11ea56d327e1133
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/scenarios_conductor/actions/runs/34160075623
images:
  - name: urban-assistant/scenarios-conductor
    newName: 10.32.11.13:5000/scenarios_conductor
    digest: sha256:7eec76f4e7eaf03572a85d76a47d394049cc83edd580c85b06b31ba24c590990
