apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/scenarios-conductor/base
  - vault-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: 577051c44f47052dbaae1d54d663b979d78d98df
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/scenarios_conductor/actions/runs/34135000927
images:
  - name: urban-assistant/scenarios-conductor
    newName: 10.32.11.13:5000/scenarios_conductor
    digest: sha256:f5c7e1c2cf2910401f4030a30d82791bb6081474100371f66f46bbee0f279789
