apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: scenarios-conductor-config
spec:
  vaultAuthRef: urban-assistant-dev
  mount: urban-assistant-kv
  type: kv-v2
  path: dev/scenarios-conductor
  refreshAfter: 1m
  hmacSecretData: true
  destination:
    create: true
    overwrite: false
    name: scenarios-conductor-config
    type: Opaque
    transformation:
      excludes: [".*"]
      templates:
        config.yaml:
          text: |
            name: scenarios-conductor
            logging:
              level: INFO
              files: []
            prometheus:
              port: 9000
              disable: false
            fileserver:
              url: {{ get .Secrets "fileserver_url" | quote }}
              bucket: scenarios.conductor
              cadastre_path: cadastre.pickle
              access_key: {{ get .Secrets "fs_access_key" | quote }}
              secret_key: {{ get .Secrets "fs_secret_key" | quote }}
            broker:
              client_id: scenarios-conductor
              group_id: scenarios-conductor-dev
              bootstrap_servers: urban-assistant-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
              schema_registry_url: http://schema-registry.kafka.svc.cluster.local:8081
              auto_offset_reset: latest
              enable_auto_commit: false
            urban_api:
              host: http://urban-api:8000
              ping_timeout_seconds: 2
              operation_timeout_seconds: 60
              auth:
                auth_server_url: {{ get .Secrets "auth_server_url" | quote }}
                realm: IDU
                client_id: scenarios-conductor
                client_secret: {{ get .Secrets "urban_api_client_secret" | quote }}
                request_timeout_seconds: 10
                refresh_before_expiry_seconds: 30
                background_refresh: true
  rolloutRestartTargets:
    - kind: Deployment
      name: scenarios-conductor
