apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/sirtep/base
  - configmap.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: 2691608728b209af12dcf316274d48eb9784d77d
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/SirtepAPI/actions/runs/35206462603
images:
  - name: urban-assistant/sirtep
    newName: 10.32.11.13:5000/sirtep
    digest: sha256:d20c0ef81276958c4e1f241380109d5a7ea875dfca6c8d5abb7caf95fce39a25
