apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: urban-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/monitor: urban-api
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
