apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/frontend/base
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: ce11e334365185e4aac62999491b78ee554e736c
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/Urban-Assistant-Client/actions/runs/34609850585
  deployment.urban-assistant/config-revision: 7f5deb6ecb7fd70e19862f9b50a58ff21cd6f264
images:
  - name: urban-assistant/frontend
    newName: 10.32.11.13:5000/urban-assistant-client
    digest: sha256:651b354eb6393eb0632d22d040e7a5086578448f662f272e3fb756567c13b115
