apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/frontend/base
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: dc6a0b69080173942df882f36b2bf790e6170a35
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/Urban-Assistant-Client/actions/runs/35874334561
  deployment.urban-assistant/config-revision: 0ae66238fe5f3fa9284e8f5e3c8efe5fc8c51873
images:
  - name: urban-assistant/frontend
    newName: 10.32.11.13:5000/urban-assistant-client
    digest: sha256:4fab5916b81cbee36e5b85a72b808a8e6bfac6b7917a0739badbefda0fae539b
