apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/frontend/base
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: 22be268b248c028600bd9dd2cab285e72400195c
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/Urban-Assistant-Client/actions/runs/35333812035
  deployment.urban-assistant/config-revision: ea0e9ada84772d22cb6cdb8d7665217d493eb120
images:
  - name: urban-assistant/frontend
    newName: 10.32.11.13:5000/urban-assistant-client
    digest: sha256:dbc2c12b3d9b2c39bbeb266fc40f1f64436709f3bb52748466915f80839b88fa
