apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: frontend-secrets
spec:
  vaultAuthRef: urban-assistant-dev
  mount: urban-assistant-kv
  type: kv-v2
  path: dev/frontend
  refreshAfter: 1m
  hmacSecretData: true
  destination:
    create: true
    overwrite: false
    name: frontend-secrets
    type: Opaque
    transformation:
      excludes: [".*"]
      templates:
        SYNAPSE_API_URL:
          text: '{{ get .Secrets "synapse_api_url" }}'
        SYNAPSE_EMAIL:
          text: '{{ get .Secrets "synapse_email" }}'
        SYNAPSE_PASSWORD:
          text: '{{ get .Secrets "synapse_password" }}'
        KEYCLOAK_AUTH_URL:
          text: '{{ get .Secrets "keycloak_auth_url" }}'
        KEYCLOAK_AUTH_REALM:
          text: '{{ get .Secrets "keycloak_auth_realm" }}'
  rolloutRestartTargets:
    - kind: Deployment
      name: urban-assistant-frontend
