apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/genplanner/base
  - configmap.yaml
  - vault-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: a98542c1684eb161443de01a876ce289ffa4b29d
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/GenPlanner/actions/runs/37013179879
images:
  - name: urban-assistant/genplanner
    newName: 10.32.11.13:5000/genplanner_api
    digest: sha256:5c1ee1836bd37ce46ccb71c7e097cbfb45cf6c98ca424491d31355de51a43904
