apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/genplanner/base
  - configmap.yaml
  - vault-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: legacy-import
images:
  - name: urban-assistant/genplanner
    newName: 10.32.11.13:5000/genplanner_api
    digest: sha256:e81bcb74aeacb39927ad2a72722b88f7eb5188cb1f3946f97b2a76e94b2c0baa
