apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/genplanner/base
  - configmap.yaml
  - vault-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: db10bae142e030caafde5d68a4388b7efd141651
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/GenPlanner/actions/runs/36573545088
images:
  - name: urban-assistant/genplanner
    newName: 10.32.11.13:5000/genplanner_api
    digest: sha256:d4c89d4562aa4877d155d43ba460dd08d58bc235ef23aae39901c0f33ececa35
