apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: genplanner-secrets
spec:
  vaultAuthRef: urban-assistant-dev
  mount: urban-assistant-kv
  type: kv-v2
  path: dev/genplanner
  refreshAfter: 1m
  hmacSecretData: true
  destination:
    create: true
    overwrite: false
    name: genplanner-secrets
    type: Opaque
    transformation:
      excludes: [".*"]
      templates:
        ECODONUT_API:
          text: '{{ get .Secrets "ecodonut_api" }}'
        OLLAMA_BASE_URL:
          text: '{{ get .Secrets "ollama_base_url" }}'
        KEYCLOAK_URL:
          text: '{{ get .Secrets "keycloak_url" }}'
        KEYCLOAK_CLIENT_SECRET:
          text: '{{ get .Secrets "keycloak_client_secret" }}'
  rolloutRestartTargets:
    - kind: Deployment
      name: genplanner
    - kind: Deployment
      name: genplanner-mcp
