apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/genbuilder/base
  - configmap.yaml
  - vault-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: 5c2501b68f5f670b56a2d6e6886ce132d4cdf49c
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/genbuilder_api/actions/runs/37318112966
images:
  - name: urban-assistant/genbuilder
    newName: 10.32.11.13:5000/genbuilder
    digest: sha256:651580839effb64d43aa48bd3864f323499655fec3e291610d48652b5b629a09
