apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/genbuilder/base
  - configmap.yaml
  - vault-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: legacy-import
images:
  - name: urban-assistant/genbuilder
    newName: 10.32.11.13:5000/genbuilder
    digest: sha256:b66732d525ddccaac418c2c732a7056458d7b7855c167126ac1052592344c10b
