apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/genbuilder/base
  - configmap.yaml
  - vault-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: 55a65f7cd1b051216c9379dc95048cf859536a9f
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/genbuilder_api/actions/runs/34980116092
images:
  - name: urban-assistant/genbuilder
    newName: 10.32.11.13:5000/genbuilder
    digest: sha256:2a91987f4033f334e1895fe89d3fbca9e827dd954d2ac620d02f6ca64fbc2346
