apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: genbuilder-secrets
spec:
  vaultAuthRef: urban-assistant-dev
  mount: urban-assistant-kv
  type: kv-v2
  path: dev/genbuilder
  refreshAfter: 1m
  hmacSecretData: true
  destination:
    create: true
    overwrite: false
    name: genbuilder-secrets
    type: Opaque
    transformation:
      excludes: [".*"]
      templates:
        Ollama_API:
          text: '{{ get .Secrets "ollama_api" }}'
        A2A_PUBLIC_URL:
          text: '{{ get .Secrets "a2a_public_url" }}'
        KEYCLOAK_URL:
          text: '{{ get .Secrets "keycloak_url" }}'
        FILESERVER_ENDPOINT:
          text: '{{ get .Secrets "fileserver_endpoint" }}'
        KEYCLOAK_CLIENT_SECRET:
          text: '{{ get .Secrets "keycloak_client_secret" }}'
        FILESERVER_ACCESS_KEY:
          text: '{{ get .Secrets "fs_access_key" }}'
        FILESERVER_SECRET_KEY:
          text: '{{ get .Secrets "fs_secret_key" }}'
  rolloutRestartTargets:
    - kind: Deployment
      name: genbuilder
