apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/chat-storage/base
  - configmap.yaml
  - vault-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: 486d742ca744a792f0be7331181bc77687b6aa73
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/ChatStorage/actions/runs/37641418371
images:
  - name: urban-assistant/chat-storage
    newName: 10.32.11.13:5000/chat_storage
    digest: sha256:0a29a557bd0eb38ce54fd7334ddaca947c42c7b7fd4886ad9944460ab765bbf6
