apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/chat-storage/base
  - configmap.yaml
  - vault-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: a19b8b795233e7f9f9b7bceccb6575abc1ebd95f
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/ChatStorage/actions/runs/37028740530
images:
  - name: urban-assistant/chat-storage
    newName: 10.32.11.13:5000/chat_storage
    digest: sha256:a71adfc3a9f19c2eb79082e75b2e6456ab61917de0f34ff72fb2fbb1340e2d99
