apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/chat-storage/base
  - configmap.yaml
  - vault-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: dcef8430e64abd56c48ce6927ec51b60aef6d3c9
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/ChatStorage/actions/runs/36150975856
images:
  - name: urban-assistant/chat-storage
    newName: 10.32.11.13:5000/chat_storage
    digest: sha256:317767b14365db02025f7d974d80390b0d3e9c149908fd1770bd39656ef2ea87
