apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: chat-storage-secrets
spec:
  vaultAuthRef: urban-assistant-dev
  mount: urban-assistant-kv
  type: kv-v2
  path: dev/chat-storage
  refreshAfter: 1m
  hmacSecretData: true
  destination:
    create: true
    overwrite: false
    name: chat-storage-secrets
    type: Opaque
    transformation:
      excludes: [".*"]
      templates:
        MONGO_URL:
          text: '{{ get .Secrets "mongo_url" }}'
        AUTH_SERVER_URL:
          text: '{{ get .Secrets "auth_server_url" }}'
        SERVICE_AUTH_SERVER_URL:
          text: '{{ get .Secrets "service_auth_server_url" }}'
        MONGO_USER:
          text: '{{ get .Secrets "mongo_user" }}'
        MONGO_PASSWORD:
          text: '{{ get .Secrets "mongo_password" }}'
        SERVICE_AUTH_CLIENT_SECRET:
          text: '{{ get .Secrets "service_auth_client_secret" }}'
  rolloutRestartTargets:
    - kind: Deployment
      name: chat-storage
