apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/gmart/base
  - configmap.yaml
  - vault-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: 96223f11e3e1c6f24eb07a14ba13a595ff9f8268
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/gMART/actions/runs/34468598035
images:
  - name: urban-assistant/gmart-agents
    newName: 10.32.11.13:5000/idu_agents
    digest: sha256:35e107d8c161aea17dc2adcc6dc06f436f754a3d065e08cd5b4203313846e871
  - name: urban-assistant/gmart-mcp
    newName: 10.32.11.13:5000/idu_mcp
    digest: sha256:01b274e8557deee6206d67acf7f401d003f61caa09c0d96cde3cbc00d90ce642
