apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/gmart/base
  - configmap.yaml
  - vault-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: 0d97d697fffdeecb0d6e2e8b5d6fd90cafae75d1
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/gMART/actions/runs/36151199541
images:
  - name: urban-assistant/gmart-agents
    newName: 10.32.11.13:5000/idu_agents
    digest: sha256:3e4c24264d9f17c0c7b02e5ae7d50c949e710b20b4ea2fa3461beb453b189c24
  - name: urban-assistant/gmart-mcp
    newName: 10.32.11.13:5000/idu_mcp
    digest: sha256:1cc0359393d5e1291da548c166ce0e5aa2f3a312523d3384c78beba9dc38884e
