apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/gmart/base
  - configmap.yaml
  - vault-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: 16c780bd53e89b909ef9a5da86d8e60bb9cff7bf
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/gMART/actions/runs/35111183234
images:
  - name: urban-assistant/gmart-agents
    newName: 10.32.11.13:5000/idu_agents
    digest: sha256:eb792c0a3157e0d4c99fe88cd6d1780ab1c5e0cd01087f412e60440be94beaa5
  - name: urban-assistant/gmart-mcp
    newName: 10.32.11.13:5000/idu_mcp
    digest: sha256:a8719f4e9b085a22e48ae735a8bcbe8b48a755e61bc71777882ffa54546c91f6
