apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/buildplanner/base
  - configmap.yaml
  - vault-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: 99c81391a19a0c144fb93d0ff1c07689927f5f13
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/BuildPlanner/actions/runs/35840254153
images:
  - name: urban-assistant/buildplanner
    newName: 10.32.11.13:5000/buildplanner
    digest: sha256:8f5357447e79568c10ec05b9ac4876c02c75481ce578df29968f954e4a8df653
