apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/buildplanner/base
  - configmap.yaml
  - vault-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: 0e02f2e3c944f272246f279d7aa774a40423d9b3
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/BuildPlanner/actions/runs/35355684782
images:
  - name: urban-assistant/buildplanner
    newName: 10.32.11.13:5000/buildplanner
    digest: sha256:8309b04a390720a49e37fe34ad975591350cf6a60d37cc4198e199dae6b6f6e9
