apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: buildplanner-secrets
spec:
  vaultAuthRef: urban-assistant-dev
  mount: urban-assistant-kv
  type: kv-v2
  path: dev/buildplanner
  refreshAfter: 1m
  hmacSecretData: true
  destination:
    create: true
    overwrite: false
    name: buildplanner-secrets
    type: Opaque
    transformation:
      excludes: [".*"]
      templates:
        KEYCLOAK_URL:
          text: '{{ get .Secrets "keycloak_url" }}'
        KEYCLOAK_CLIENT_SECRET:
          text: '{{ get .Secrets "keycloak_client_secret" }}'
        LLM_API:
          text: '{{ get .Secrets "llm_api" }}'
        MINIO_ADDRESS:
          text: '{{ get .Secrets "minio_address" }}'
        MINIO_ACCESS_KEY:
          text: '{{ get .Secrets "minio_access_key" }}'
        MINIO_SECRET_KEY:
          text: '{{ get .Secrets "minio_secret_key" }}'
        PUBLIC_BASE_URL:
          text: '{{ get .Secrets "public_base_url" }}'
  rolloutRestartTargets:
    - kind: Deployment
      name: buildplanner
