apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/pzz-compare/base
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: f4d2c55d5d2b5294b15c5d680fade1a626ce6d73
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/PzzCompareAPI/actions/runs/36573336245
images:
  - name: urban-assistant/pzz-compare
    newName: 10.32.11.13:5000/pzz-pipeline
    digest: sha256:6d51de562aabc847fc35aafd5bf594d19cab6221dceb9379c51439934c4be255
