apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/pzz-compare/base
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: d037abe99eab1c44ca0db22bf9bc46793e60d9ed
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/PzzCompareAPI/actions/runs/34217106356
images:
  - name: urban-assistant/pzz-compare
    newName: 10.32.11.13:5000/pzz-pipeline
    digest: sha256:20cddc92b21df9698651dd12eb369974bff464d6b2930f4ad2509c74cc9f0f9e
