#!/usr/bin/env python3
"""Render deterministic PostSync Jobs; --check is used by CI to prevent drift."""

import argparse
import json
from pathlib import Path

import yaml


class Dumper(yaml.SafeDumper):
    def increase_indent(self, flow=False, indentless=False):
        return super().increase_indent(flow, False)


def string(dumper, value):
    return dumper.represent_scalar("tag:yaml.org,2002:str", value, style="|" if "\n" in value else None)


Dumper.add_representer(str, string)


def job(root, service):
    name = service["name"]
    frontend = name == "frontend"
    script = (root / "scripts" / ("frontend-smoke.mjs" if frontend else "smoke-probe.py")).read_text(encoding="utf-8")
    # Reuse the application's own image, so no extra public image is required on
    # cluster nodes. Override its entrypoint; never import application config.
    image = next(i for i in service["images"] if i["alias"] != "migrator")
    labels = {"app.kubernetes.io/name": f"{name}-smoke-test", "app.kubernetes.io/component": "smoke-test"}
    return {
        "apiVersion": "batch/v1", "kind": "Job",
        "metadata": {"name": f"{name}-smoke-test", "labels": labels, "annotations": {
            "argocd.argoproj.io/hook": "PostSync",
            "argocd.argoproj.io/hook-delete-policy": "BeforeHookCreation,HookSucceeded",
        }},
        "spec": {"backoffLimit": 0, "activeDeadlineSeconds": 300, "template": {
            "metadata": {"labels": labels},
            "spec": {"restartPolicy": "Never", "enableServiceLinks": False,
                     "automountServiceAccountToken": False, "containers": [{
                         "name": "smoke-test", "image": image["kustomizeName"] + ":base",
                         "imagePullPolicy": "IfNotPresent",
                         "command": ["node", "--input-type=module", "-e"] if frontend else ["python", "-c"],
                         "args": [script], "env": [{"name": "SMOKE_CHECKS", "value": json.dumps(service["smokeChecks"], separators=(",", ":"))}],
                         "resources": {"requests": {"cpu": "10m", "memory": "32Mi"},
                                       "limits": {"cpu": "200m", "memory": "128Mi"}},
                         "securityContext": {"allowPrivilegeEscalation": False, "capabilities": {"drop": ["ALL"]},
                                             "seccompProfile": {"type": "RuntimeDefault"}},
                     }]},
        }},
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--patch", action="store_true", help="Print an apply_patch patch without writing files")
    args = parser.parse_args()
    root = args.root.resolve()
    catalog = yaml.safe_load((root / "services.yaml").read_text(encoding="utf-8"))
    mismatches = []
    patches = []
    for service in catalog["services"]:
        path = root / "apps" / service["name"] / "base" / "post-sync-smoke-test.yaml"
        # Ignore aliases in generated YAML, even when the same labels dict is reused.
        Dumper.ignore_aliases = lambda self, data: True
        text = "# Generated by scripts/generate-smoke-tests.py; edit services.yaml or scripts/smoke-probe.py.\n"
        text += yaml.dump(job(root, service), Dumper=Dumper, sort_keys=False, width=120, allow_unicode=True)
        if args.patch:
            if path.is_file():
                old = path.read_text(encoding="utf-8")
                if old == text:
                    continue
                patches.append(f"*** Update File: {path.as_posix()}\n@@\n" +
                               "\n".join("-" + line for line in old.splitlines()) + "\n" +
                               "\n".join("+" + line for line in text.splitlines()))
            else:
                patches.append(f"*** Add File: {path.as_posix()}\n" +
                               "\n".join("+" + line for line in text.splitlines()))
        elif args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != text:
                mismatches.append(str(path.relative_to(root)))
        else:
            path.write_text(text, encoding="utf-8", newline="\n")
    if mismatches:
        raise SystemExit("Regenerate smoke tests: " + ", ".join(mismatches))
    if args.patch:
        print("*** Begin Patch\n" + "\n".join(patches) + "\n*** End Patch")
    else:
        print(f"{'Checked' if args.check else 'Generated'} {len(catalog['services'])} smoke jobs")


if __name__ == "__main__":
    main()
