replicas: 1
watchNamespaces:
  - kafka
watchAnyNamespace: false
defaultImageTag: 1.1.0
resources:
  requests:
    cpu: 200m
    memory: 384Mi
  limits:
    cpu: "1"
    memory: 768Mi
podDisruptionBudget:
  enabled: false
operatorNetworkPolicy:
  enabled: false
generateNetworkPolicy: true
generatePodDisruptionBudget: true
