apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: object-effects
spec:
  selector:
    matchLabels:
      app.kubernetes.io/monitor: object-effects
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
