apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/urban-mcp/base
  - vault-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: legacy-import
images:
  - name: urban-assistant/urban-mcp
    newName: 10.32.11.13:5000/urban_mcp
    digest: sha256:cfdc00b99226d5f2a016051750b39022546c361632a31e85eb73a36fa61afbd9
