apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/urban-mcp/base
  - vault-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: 7fe385fcb1ec6b96366abd0ac95d36ba1fa258e8
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/idu_api/actions/runs/34150930439
images:
  - name: urban-assistant/urban-mcp
    newName: 10.32.11.13:5000/urban_mcp
    digest: sha256:49562115734d5573ab6950e3fc67bbb7165a3e64b3bba69569a6976fae6090e5
