apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/urban-mcp/base
  - vault-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: e76ef1951c0313b6c0282bca8211b6bc26a33b2e
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/idu_api/actions/runs/35585828674
images:
  - name: urban-assistant/urban-mcp
    newName: 10.32.11.13:5000/urban_mcp
    digest: sha256:45c6f1abdeff27fe1a7522680e6a4acae5eb04ede37cb715d8d214fbc321accb
