apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/normgraph/base
  - configmap.yaml
  - vault-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: 48ef6bf349f745173043d3463638c28d6113e01d
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/NormGraph/actions/runs/36349168873
images:
  - name: urban-assistant/normgraph
    newName: 10.32.11.13:5000/normgraph
    digest: sha256:754eac460f391aa249f6e2375a2f1af6ff1685ab55a5efe49e468bbd2ccff436
