apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/normgraph/base
  - configmap.yaml
  - vault-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: 3ab153980a56d55463d51801f8cbe37b9a5c0243
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/NormGraph/actions/runs/37335952591
images:
  - name: urban-assistant/normgraph
    newName: 10.32.11.13:5000/normgraph
    digest: sha256:fa572b8c258d7cc146779dd507fc98b77aec334a010daac14e8f07b9b71dd4f8
