apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/idu-dvd/base
  - configmap.yaml
  - vault-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: 28cc5c1efdf20a37486cece51b020ca0271b0819
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/IDU_DVD/actions/runs/34788059342
images:
  - name: urban-assistant/idu-dvd
    newName: 10.32.11.13:5000/idu_dvd
    digest: sha256:673fcd0006ac6e708714c328f84c552feb70f69164b48bbbcb28814ce524210b
