apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/idu-dvd/base
  - configmap.yaml
  - vault-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: 1bc1c0d5fb7020fbf2ad4e66198afa2f901390c6
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/IDU_DVD/actions/runs/34218035993
images:
  - name: urban-assistant/idu-dvd
    newName: 10.32.11.13:5000/idu_dvd
    digest: sha256:d86ea9a8af4a470faf8411a733e247bfee1acf14d0808c01682258f0b2b885c0
