apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urban-assistant-dev
resources:
  - ../../../../apps/idu-dvd/base
  - configmap.yaml
  - vault-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: urban-assistant
      environment: dev
    includeSelectors: false
commonAnnotations:
  deployment.urban-assistant/source-revision: 9dcb326ffdc5601542e4cb1d282d582b2114e492
  deployment.urban-assistant/source-workflow: https://github.com/IDUclub/IDU_DVD/actions/runs/37323660102
images:
  - name: urban-assistant/idu-dvd
    newName: 10.32.11.13:5000/idu_dvd
    digest: sha256:b08949703b17b62847fd65b0a707aca0bc7ad869f105efb402aca6298c3d683c
